### ISSUE TITLE
Frontend edit field

### ISSUE THREAD

**Issue by johanneslamers** [elivz/VzAddress-Craft#1]
Hi Eli

Is it possible to edit the field from the frontend?

 <input type="input" class="form-control" id="profile-telefoon" placeholder="Postcode" name="fields[adresFull.postalCode]" value="{{ user.adresFull.postalCode  }}">

This is not updating the field.

**Comment by elivz** [comment]
Can you show me the HTML you are using in your form? You need to make sure to match the field names for the individual components of the address - probably easies to view source in the back-end and copy from there.
