### ISSUE TITLE
getTemplatesPath() / setTemplatesPath() deprecation errors

### ISSUE THREAD

**Issue by cavellblood** [elivz/VzAddress-Craft#11]
On Craft 2.6.2778 there are the following deprecation errors related to this plugin: 

`PathService::getTemplatesPath() has been deprecated. Use TemplatesService::getTemplatesPath() or TemplatesService::getTemplateMode() instead.`

Pixel & Tonic have posted [a solution on StackExchange](http://craftcms.stackexchange.com/questions/14375/how-do-i-fix-gettemplatespath-settemplatespath-deprecation-errors/14380). Here is the [changelog for 2.6.2778](https://craftcms.com/changelog#build2778) also. Hope this helps!

**Comment by elivz** [comment]
Thanks for the heads-up! This is fixed in version 1.0.3, which will be released shortly.
