### ISSUE TITLE
Craft Exception when trying to use the staticMap.

### ISSUE THREAD

**Issue by janson** [elivz/VzAddress-Craft#13]
The error: `Craft\VzAddress_AddressModel and its behaviors do not have a method or closure named "inline".`

And the stack trace begins with:
`plugins/vzaddress/models/VzAddress_AddressModel.php(148): Craft\BaseModel->__call("inline", array())`

**Comment by elivz** [comment]
This is fixed in 1.0.4. Sorry for the long delay...I have been away from work for a while.
