### ISSUE TITLE
Use with A&M Forms?

### ISSUE THREAD

**Issue by britizen** [elivz/VzAddress-Craft#14]
When using your plug-in with A&M Forms, the fields are not displaying using the auto generated code. Is there some syntax I need to use to get these to show?

**Comment by elivz** [comment]
Apologies for the very late response. I am sure you have already found another solution at this point, but for future reference: A&M Forms only displays its built-in "Basic" fieldtypes in the auto-generated code. There isn't (as far as I can tell) any way for 3rd-party fieldtypes to hook in and add ourselves to the list of supported fieldtypes. So you would need to use the Custom HTML method, and add your own HTML code for the address field - which you can copy from another VZ Address field and just update the input names. It's kind of a pain, I'm afraid, but there isn't currently any better solution with A&M Forms. You could always open a support request with A&M asking that they add that capability in the future...no idea if it is something they are considering or would consider.
