### ISSUE TITLE
staticMap and staticMapUrl Being Output Multiple Times

### ISSUE THREAD

**Issue by RitterKnightCreative** [elivz/VzAddress-Craft#15]
In [vzaddress/models/VzAddress_AddressModel.php](https://github.com/elivz/VzAddress-Craft/commit/cc4f5ed86f2dcca54d8398a0c6d8accceeb63ab7#diff-24765016bafd0f1fe80312806741d28eR139)

Looks like this line is causing it:

`$output .= $key ? $output.'&key='.$key : $output`

Should be:

`$output = $key ? $output.'&key='.$key : $output`

Easy fix!

**Comment by elivz** [comment]
Duh. Fixed now.
