### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by steve71p** [elivz/VzAddress-Craft#18]
Hi, I updated VzAddress and I get this error 
Parse error: syntax error, unexpected craft/plugins/vzaddress/VzAddressPlugin.php on line 47

The previous version and it is working is 1.0.5
my carft version is Craft CMS 2.6.2950

any solutions?
thanks
steve

**Comment by elivz** [comment]
You must be running PHP 5.3? I had used the newer array syntax introduced in PHP 5.4, but there was no real need for it, so I just published v1.1.1 which reverts to the old syntax.

**Comment by steve71p** [comment]
sad but true, still on php 5.3... thanks so much

**Comment by elivz** [comment]
It's okay....I'm only judging you a little :)
