### ISSUE TITLE
Solspace Calendar Conflict?

### ISSUE THREAD

**Issue by worshiplive** [elivz/VzAddress-Craft#25]
Not sure but when I have the plugin enabled and I try to look at a previous entry that I did in Solspace calendar I get a 500 error on the page.  I disable VzAddress and all is good again.  Any ideas on what the cause could be.

**Comment by worshiplive** [comment]
I switched to PHP 7.1 from PHP 5.3.6 and the issue resolved.

**Comment by elivz** [comment]
Glad you got it working. I will add a note to make it more clear that PHP 5.3 isn't supported.
