### ISSUE TITLE
Get country code list from template

### ISSUE THREAD

**Issue by tobystokes** [elivz/VzAddress-Craft#27]
Great plugin (I use it's dadEE too!)

Is it possible to get a full list of all the country codes in a twig front end template?

I'm trying to make a form to search for addresses, and while the following generates the correct output:
```
{% set countryCodes = ['AF', 'AX', 'AL', 'DZ', '..........', 'ZM', 'ZW'] %}
{% set localeData = craft.i18n.getLocaleData() %}
<select name="country">
  {% for country in countryCodes %}
    <option value="{{ country }}">{{ localeData.getTerritory(country) }}</option>
  {% endfor %}
</select>
```

I'd rather not duplicate that entire country list from your fieldtype.

**Comment by elivz** [comment]
That's a very good idea, and should be easy to implement. I will try to get a release out with that addition in the next day or two.

**Comment by elivz** [comment]
This is added in [v1.5.0](https://github.com/elivz/VzAddress-Craft/archive/1.5.0.zip). You can access the array of countries using `craft.vzAddress.countries`. So your example above would become:

    <select name="country">
        {% for countryCode, countryName in craft.vzAddress.countries %}
            <option value="{{ countryCode }}">{{ countryName }}</option>
        {% endfor %}
    </select>

**Comment by tobystokes** [comment]
nice!
