### ISSUE TITLE
Error outputting dynamic Google Map

### ISSUE THREAD

**Issue by artmem** [elivz/VzAddress-Craft#29]
I'm trying to output a dynamic map using this code:
`{{ contact.address.dynamicMap() }}`
On my local machine, it works fine, but uploaded to my server, I just get a grey box and these two js errors, referencing maps.googleapis.com:
Line 35:336 InvalidValueError: setPosition: not a LatLng or LatLngLiteral: not an Object
Line 35:336 InvalidValueError: setCenter: not a LatLng or LatLngLiteral: not an Object

**Comment by elivz** [comment]
Did you create an API key and enter it in the plugin settings? Without a valid API key, Google won't geocode the address into a set of coordinates, which would explain that error. Your local machine was probably grandfathered in from before last year when they started requiring a key for all API access.

Let me know if that wasn't the problem, and I'll see what else I can come up with. I will be traveling the next few days though, so I might not be able to respond until the weekend.

**Comment by artmem** [comment]
Now I'm more confused. I did create an API key. I tested it last night from home, and the map worked fine. Now, I'm back at work, and it isn't working on multiple computers. I thought it might be a network issue, but it isn't loading on my phone, either. I have no idea what's going on. The site is dev.crasianbrewing.com

**Comment by elivz** [comment]
Can you try [downloading the current version from GitHub](https://github.com/elivz/VzAddress-Craft/archive/master.zip)? I think I found the problem, but I want to confirm that it's fixed before I release it officially.

**Comment by artmem** [comment]
Thanks. I just left for vacation, so I won't be able to test it until the 15th.  I'll let you know if it works.

**Comment by artmem** [comment]
Just installed the new version. Now it just displays a message that a Google API key is required, even though I have one, and it shows up in the plugin settings.

**Comment by elivz** [comment]
Nathaniel,

I have not been able to duplicate this with the current version. Is there any change I could get access to your site to try a couple things? If so, you can email me at eli@elivz.com. I'm not sure what is different between your setup and my test sites....

**Comment by curtishenson** [comment]
Just ran into the "Google API key is required" issue, I think it's an error in the logic for grabbing the key. Submitted a pull request of what I _think_ is the fix.

**Comment by artmem** [comment]
Sorry, I stopped getting updates from this thread, for some reason. Eli, I just emailed you info tho access my site.

**Comment by elivz** [comment]
I just merged a pull request from @curtishenson (thanks!) that should fix this for you.
