### ISSUE TITLE
on _entry template, everything returns null

### ISSUE THREAD

**Issue by lenchantin** [elivz/VzAddress-Craft#8]
I'm trying to return an address. I can't get any field to return without an error.

{{ entry.eventAddress.html }}
returns the error "Impossible to access an attribute ("html") on a null variable" -- returns the same thing with "street" or "name" or anything else.

**Comment by elivz** [comment]
For some reason, the eventAddress field isn't getting passed into your template (thus, null). Are you certain that field is assigned to the entry you are viewing? 

You could handle potentially non-existent address by wrapping the address tags with:

```
{% if entry.eventAddress is defined %}
  {{ entry.eventAddress.html }}
{% endif %}
```
