### ISSUE TITLE
Possible to wrap each line with `<li>` tags?

### ISSUE THREAD

**Issue by andregoldstein** [elivz/VzAddress-Craft#9]
Hi there, possible feature request, as above, would it be feasible to offer an `<li>` tag output?

Thanks

**Comment by elivz** [comment]
Hey Andre,

I will consider this for a future release, but to be honest I'm not entirely sold on it as a core feature. However it is very easy to use your own template for rendering the address in whatever format you want! Just use one of the templates files from vzaddress/templates/_frontend as an example. Save it into your templates folder and then include it wherever you want to render the address, passing in your address field like this:

### templates/_partials/address.twig

``` twig
<ul>
  {% if address.name %}<li>{{ address.name }}</li>{% endif %}
  {% if address.street %}<li>{{ address.street }}</li>{% endif %}
  {% if address.street2 %}<li>{{ address.street2 }}</li>{% endif %}
  <li>
    {% if address.city %}{{ address.city }}, {% endif %}
    {{ address.region }} {{ address.postalCode }}
  </li>
  {% if includeCountry %}<li>{{ address.countryName }}</li>{% endif %}
</ul>
```

### Wherever you want to display an address:

``` twig
{% include '_partials/address' with { entry.addressField as address} only %}
```

**Comment by andregoldstein** [comment]
Thanks very much Eli! I guess the use case is that when creating a design I
would tend to use an unordered list to display an address more often than
`<p>` tags with `<br>` tags.

Thanks for the tip though on the partial!

On 17 February 2016 at 19:50, Eli Van Zoeren notifications@github.com
wrote:

> Hey Andre,
> 
> I will consider this for a future release, but to be honest I'm not
> entirely sold on it as a core feature. However it is very easy to use your
> own template for rendering the address in whatever format you want! Just
> use one of the templates files from vzaddress/templates/_frontend as an
> example. Save it into your templates folder and then include it wherever
> you want to render the address, passing in your address field like this:
> templates/_partials/address.twig
> 
> <ul>
>   {% if address.name %}<li>{{ address.name }}</li>{% endif %}
>   {% if address.street %}<li>{{ address.street }}</li>{% endif %}
>   {% if address.street2 %}<li>{{ address.street2 }}</li>{% endif %}
>   <li>
>     {% if address.city %}{{ address.city }}, {% endif %}
>     {{ address.region }} {{ address.postalCode }}
>   </li>
>   {% if includeCountry %}<li>{{ address.countryName }}</li>{% endif %}
> </ul>
> 
> Wherever you want to display an address:
> 
> {% include '_partials/address' with { entry.addressField as address} only %}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elivz/VzAddress-Craft/issues/9#issuecomment-185374063
> .

## 

_André Goldstein_
_Director, Milktop_

_http://www.milktop.co.uk http://www.milktop.co.uk_
@MilktopDesign https://twitter.com/MilktopDesign
